name: Generate Pacman Animation

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Rename folder to output
        run: mv dist output

      - name: Commit and push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update pacman contribution graph"
          file_pattern: output/*
